In [1]:
import numpy as np
import pandas as pd

In [3]:
sale1 = pd.read_excel('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/판매분석/판매성과/판매성과_2023-07-17_2023-12-31.xlsx')
sale2 = pd.read_excel('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/판매분석/판매성과/판매성과_2024-01-01_2024-06-30.xlsx')

/Users/kang_hiee/miniforge3/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/kang_hiee/miniforge3/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [7]:
sales = pd.concat([sale2, sale1], axis=0)

In [9]:
sales.to_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/판매분석/판매성과/sales.csv', index=False)

In [11]:
sales.columns

Index(['날짜', '요일', '시간대', '결제자수', '결제수', '모바일비율(결제건수)', '결제금액', '모바일비율(결제금액)',
       '결제당 결제금액', '결제상품수량', '결제당 상품수량', '배송비', '쿠폰합계', '상품쿠폰', '주문쿠폰', '환불건수',
       '환불금액', '환불비율(결제금액)', '환불수량', '환불비율(결제상품수량)'],
      dtype='object')

In [12]:
sales.head(1)

,날짜,요일,시간대,결제자수,결제수,모바일비율(결제건수),결제금액,모바일비율(결제금액),결제당 결제금액,결제상품수량,결제당 상품수량,배송비,쿠폰합계,상품쿠폰,주문쿠폰,환불건수,환불금액,환불비율(결제금액),환불수량,환불비율(결제상품수량)
0,2024-06-29,토,09시,1,1,1.0,489000,1.0,489000.0,100,100.0,0,1000,1000,0,0,0,0.0,0,0.0

In [15]:
product1 = pd.read_excel('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/판매분석/상품성과/상품성과_2023-07-17_2023-12-31.xlsx')
product2 = pd.read_excel('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/판매분석/상품성과/상품성과_2024-01-01_2024-06-30.xlsx')
products = pd.concat([product1, product2], axis=0)
products.to_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/판매분석/상품성과/products.csv', index=False)

/Users/kang_hiee/miniforge3/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/kang_hiee/miniforge3/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [16]:
delivery1 = pd.read_excel('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/판매분석/배송통계/배송통계_2023-07-17_2023-12-31.xlsx')
delivery2 = pd.read_excel('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/판매분석/배송통계/배송통계_2024-01-01_2024-06-30.xlsx')
deliverys = pd.concat([delivery1,delivery2], axis=0)
deliverys.to_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/판매분석/배송통계/deliverys.csv', index=False)

/Users/kang_hiee/miniforge3/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/kang_hiee/miniforge3/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
import pandas as pd
customer1 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20230717_20230816.csv')
customer2 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20230817_20230916.csv')
customer3 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20230917_20231017.csv')
customer4 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20231018_20231117.csv')
customer5 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20231118_20231218.csv')
customer6 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20231219_20240118.csv')
customer7 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20240119_20240218.csv')
customer8 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20240219_20240319.csv')
customer9 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20240320_20240419.csv')
customer10 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20240420_20240520.csv')
customer11 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20240521_20240620.csv')
customer12 = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/통계_고객현황_20240621_20240630.csv')
customers = pd.concat([customer1,customer2, customer3, customer4, customer5, customer6, customer7, customer8, customer9, customer10, customer11, customer12], axis=0)
customers.to_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/고객현황/customers.csv', index=False)

In [7]:
sales = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/판매분석/판매성과/sales.csv')

In [8]:
sales

,날짜,요일,시간대,결제자수,결제수,모바일비율(결제건수),결제금액,모바일비율(결제금액),결제당 결제금액,결제상품수량,결제당 상품수량,배송비,쿠폰합계,상품쿠폰,주문쿠폰,환불건수,환불금액,환불비율(결제금액),환불수량,환불비율(결제상품수량)
0,2024-06-29,토,09시,1,1,1.0,489000,1.0,489000.0,100,100.0,0,1000,1000,0,0,0,0.0,0,0.0
1,2024-06-27,목,22시,1,1,1.0,126400,1.0,126400.0,26,26.0,0,1000,1000,0,0,0,0.0,0,0.0
2,2024-06-26,수,14시,1,2,1.0,42000,1.0,21000.0,3,1.5,3000,0,0,0,0,0,0.0,0,0.0
3,2024-06-26,수,13시,1,1,1.0,27000,1.0,27000.0,2,2.0,3000,1000,1000,0,0,0,0.0,0,0.0
4,2024-06-25,화,20시,1,1,1.0,959000,1.0,959000.0,100,100.0,0,1000,1000,0,0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,2023-07-24,월,17시,1,1,0.0,63000,0.0,63000.0,3,3.0,0,0,0,0,0,0,0.0,0,0.0
630,2023-07-23,일,23시,1,1,1.0,200000,1.0,200000.0,50,50.0,6000,0,0,0,0,0,0.0,0,0.0
631,2023-07-20,목,18시,1,1,1.0,43000,1.0,43000.0,2,2.0,0,0,0,0,0,0,0.0,0,0.0
632,2023-07-20,목,19시,1,1,0.0,22000,0.0,22000.0,2,2.0,9000,0,0,0,0,0,0.0,0,0.0
633,2023-07-17,월,09시,1,1,1.0,75000,1.0,75000.0,3,3.0,4000,0,0,0,0,0,0.0,0,0.0

In [9]:
products = pd.read_csv('/Users/kang_hiee/Documents/강희/유비온/최종프로젝트/판매분석/상품성과/products.csv')

In [11]:
products.head(1)

,상품카테고리(대),상품카테고리(중),상품카테고리(소),상품카테고리(세),상품명,상품ID,결제수,결제상품수량,모바일비율(결제상품수량),결제금액,모바일비율(결제금액),상품수당 결제금액,쿠폰합계,상품쿠폰,주문쿠폰,환불건수,환불금액,환불비율(결제금액),환불수량,환불비율(결제상품수량)
0,식품,과자/베이커리,강정,-,후백 호두강정 80g 결혼 돌잔치 장례 행사 답례품,8959294188,30,1574,0.756036,7102900,0.770587,4512.642948,5000,5000,0,2,555000,0.078137,130,0.082592

In [12]:
products.groupby(['상품명'])['결제수'].sum()

상품명
고급 답례 호두강정(낱개포장)                                   3
고급 답례품 호두강정 1구 (170g)                             13
고급 답례품 호두강정 1구 170g                                7
고급 답례품 호두강정 2구 (170gx2)                           29
고급 답례품 호두강정 2구 170gx2                              5
고급 답례품 호두강정 3구 (170gx3)                           37
고급 답례품 호두강정 3구 170gx3                             13
고급 보자기 답례품 호두강정 3구 170gx3                          1
고급답례 호두강정 미니원통형(80g)                               3
고급답례 호두강정 소포장15gx4봉(60g)                           2
고급선물용 호두30%포함 호두쿠키&호두강정 모두다세트                      1
낱개포장형 고급답례품 (호두30%함유)호두쿠키12개+호두강정6개                3
낱개포장형 고급답례품 호두쿠키 & 호두강정                            2
단체 고급 간식세트 호두강정 & 호두쿠키                             7
신제품 이벤트 고급 답례 호두강정 미니원통형(80g)                     12
실속형 호두쿠키 낱개포장 22g x 10개(220g)                      3
호두강정 실속형 3팩 (120g x 3)                            25
호두강정 실속형 3팩 120g x 3                               2
호두쿠키 낱개포장 22g x 10개(220g)                         10
혼합 고급답례품 호두강정&호두쿠키(호두30%함유)                       24
후백 HU100 호두강정 낱개포장 12개                            13
후백 HU100 호두강정 답례품 낱개포장(3봉)                        14
후백 HU100 호두강정 정과 답례품 80g 결혼 돌잔치 장례 단체행사          155
후백 HU100 호두강정 호두정과 1구 170g                        24
후백 HU100 호두강정 호두정과 4구 이바지, 상견례 고급선물               13
후백 HU100 호두강정 호두정과 답례품 2구                         18
후백 HU100 호두강정 호두정과 답례품 3구                         14
후백 HU100 호두강정 호두정과 답례품 80g 결혼 돌잔치 장례 단체행사         42
후백 HU100 호두강정 호두정과 답례품 결혼 장례 조문 돌잔치 단체행사 170g      5
후백 HU100 호두강정 호두정과 답례품 결혼 장례 조문 돌잔치 단체행사 80g      19
후백 HU100 호두강정 호두정과 실속형 3팩 120g x 3                32
후백 HU100 호두쿠키 낱개포장 10개                             1
후백 고급 간식세트 호두강정 호두쿠키                               1
후백 고급답례품 세트 호두강정 호두쿠키                              1
후백 호두강정 1구 (170g)                                  3
후백 호두강정 1구 170g                                   13
후백 호두강정 80g 결혼 돌잔치 장례 행사 답례품                      54
후백 호두강정 80g 기분좋은 답례품                               1
후백 호두강정 고급 답례품 3구                                 29
후백 호두강정 고급 답례품 4구 선물세트                             5
후백 호두강정 낱개포장 12개                                   5
후백 호두강정 답례품 2구                                    33
후백 호두강정 실속형 3팩 120g x 3                           18
후백 호두강정 정과 답례품 80g 결혼 돌잔치 장례 단체행사                  9
후백 호두강정 정과 답례품 80g 결혼 돌잔치 장례 행사                   42
후백 호두강정 정과 답례품 결혼 돌잔치 장례 행사 80g                    4
후백 호두강정 호두정과 1구 170g                               1
후백 호두강정 호두정과 답례품 2구                                2
후백 호두강정 호두정과 답례품 3구                                2
후백 호두강정 호두정과 답례품 4구                                2
휴대용 호두강정 낱개포장 15g x 12개(200g)                     19
Name: 결제수, dtype: int64